name: 'build'
on:
  push:
    branches:
      - 'v1'
  pull_request:
    branches:
      - 'v1'
jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [ '8', '11' ]
      fail-fast: false
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'coursier/cache-action@v5'
      - uses: 'olafurpg/setup-scala@v10'
        with:
          java-version: ${{ matrix.java }}
      - name: 'Compile, test, and check binary compatibility'
        run: "sbt clean +compile +test +mimaReportBinaryIssues"
